name:                gcl
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/scmlab/gcl
license:             BSD3
author:              Author name here
maintainer:          banacorn@gmail.com
copyright:           something
category:            language
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -fno-warn-orphans

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - megaparsec >= 8.0
  - free
  - parser-combinators
  - prettyprinter
  - mtl
  - srcloc
  - text
  - lexer-applicative
  - regex-applicative
  - random

library:
  source-dirs: src

executables:
  gcl:
    main: Main.hs
    source-dirs: app
    dependencies:
      - gcl

tests:
  gcl-test:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
