name:                gcl
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/scmlab/gcl
license:             BSD3
author:              Author name here
maintainer:          banacorn@gmail.com
copyright:           something
category:            language
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - megaparsec >= 8.0
  - free
  - parser-combinators
  - prettyprinter
  - mtl
  - network
  - network-simple
  - srcloc
  - text
  - lexer-applicative
  - regex-applicative
  - random
  - vector
  - lsp 
  - multiset
  - transformers

library:
  source-dirs: src

  ghc-options:
    - -Wall
    - -fno-warn-orphans

executables:
  gcl:
    main: Main.hs
    source-dirs: app
    dependencies:
      - gcl

    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fno-warn-orphans


tests:
  gcl-test:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-golden
      - tasty-quickcheck

    ghc-options:
      - -Wall
      - -fno-warn-orphans
