# modified from https://github.com/simonmichael/hledger/blob/master/.github/workflows/release.yml

# Creates a draft github release.
# See https://github.com/actions/create-release, still pretty rough as of 20200609.
# see also: https://github.com/marketplace/actions/tag-release-on-push-action

name: Create draft release

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
        
      # - name: Upload Release Asset
        # uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        # with:
        #   files: Release.txt
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./gcl-linux.zip
          asset_name: gcl-linux.zip
          asset_content_type: application/zip

    # steps:
    #   - name: Download math result for job 2
    #     uses: actions/download-artifact@v2
    #     with:
    #       name: homework
    #   - name: Print the final result
    #     shell: bash
    #     run: |
    #       value=`cat math-homework.txt`
    #       echo The result is $value